# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: gomod
    directory: "/chain"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "github.com/tendermint/tendermint"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "github.com/cosmos/ibc-go"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 2
