VERSION 0.6
FROM node:lts-alpine
WORKDIR /app

# Frontend
frontend-context:
    COPY package.json package-lock.json lerna.json ./
    COPY ./empowerjs/+project-setup/* empowerjs/
    COPY proof-of-existence proof-of-existence
    COPY marketplace marketplace
    SAVE ARTIFACT .

frontend-install:
    FROM +frontend-context
    RUN npm ci

lerna-build:
    FROM +frontend-install
    RUN npx lerna run build