const API_ENDPOINT = import.meta.env.VITE_API_ENDPOINT;
const HTTPS_FILE_URL = import.meta.env.VITE_HTTPS_FILE_URL;
const RPC_ENDPOINT = import.meta.env.VITE_RPC_ENDPOINT;
const MARKETPLACE_CONTRACT = import.meta.env.VITE_MARKETPLACE_CONTRACT;
const CHAIN_ID = import.meta.env.VITE_CHAIN_ID;
export {API_ENDPOINT, HTTPS_FILE_URL, RPC_ENDPOINT, MARKETPLACE_CONTRACT, CHAIN_ID};
