const API_ENDPOINT = import.meta.env.VITE_API_ENDPOINT;
const HTTPS_FILE_URL = import.meta.env.VITE_HTTPS_FILE_URL;
const RPC_ENDPOINT = import.meta.env.VITE_RPC_ENDPOINT;
const REST_ENDPOINT = import.meta.env.VITE_REST_ENDPOINT;
const MARKETPLACE_CONTRACT = import.meta.env.VITE_MARKETPLACE_CONTRACT;
const CHAIN_ID = import.meta.env.VITE_CHAIN_ID;
const CHAIN_NAME = import.meta.env.VITE_CHAIN_NAME;
const DEFAULT_CREDIT_TYPE = import.meta.env.VITE_DEFAULT_CREDIT_TYPE;
const GOOGLE_MAPS_API_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;
const REVISION_ID = import.meta.env.VITE_REVISION_ID;
const ENVIRONMENT = import.meta.env.VITE_ENVIRONMENT;
const ROLLBAR_ACCESS_TOKEN = import.meta.env.VITE_ROLLBAR_ACCESS_TOKEN;
export {
  API_ENDPOINT,
  HTTPS_FILE_URL,
  RPC_ENDPOINT,
  REST_ENDPOINT,
  MARKETPLACE_CONTRACT,
  CHAIN_ID,
  CHAIN_NAME,
  DEFAULT_CREDIT_TYPE,
  GOOGLE_MAPS_API_KEY,
  REVISION_ID,
  ENVIRONMENT,
  ROLLBAR_ACCESS_TOKEN,
};
