const RPC_ENDPOINT = import.meta.env.VITE_RPC_ENDPOINT;
const TESTNET_RPC_ENDPOINT = import.meta.env.VITE_TESTNET_RPC_ENDPOINT;
const REST_ENDPOINT = import.meta.env.VITE_REST_ENDPOINT;
const CHAIN_ID = import.meta.env.VITE_CHAIN_ID;

export {
  RPC_ENDPOINT,
  REST_ENDPOINT,
  TESTNET_RPC_ENDPOINT,
  CHAIN_ID,
};
