VERSION 0.6
FROM node:lts-alpine
WORKDIR /empowerchain/frontend/ts-client

generate-ts-types:
    COPY . .
    COPY ../../+get-proto/* ./proto
    RUN npm i
    RUN npx telescope transpile --protoDirs=./proto --outPath=./src/codegen --includeAminos=true --includeLCDClients=true --includeRPCClients=true
    SAVE ARTIFACT ./src/codegen AS LOCAL ./src/codegen