VERSION 0.6
FROM node:lts-alpine
WORKDIR /empowerchain/frontend/empowerjs

install-ts-codegen:
  RUN npm install -g @cosmwasm/ts-codegen@0.25.2

cosmwasm-codegen:
  FROM +install-ts-codegen
  COPY ../../+get-cw-schema/* .
  RUN cosmwasm-ts-codegen generate \
    --plugin client \
    --schema ./schema \
    --out ./src/plastic-credit-marketplace \
    --name "Plastic Credit Marketplace" \
    --bundle true \
    --bundleFile index.ts \
    --bundleScope contracts
  SAVE ARTIFACT ./src/plastic-credit-marketplace AS LOCAL ./src/plastic-credit-marketplace

proto-codegen:
    COPY . .
    COPY ../../+get-proto/* ./proto
    RUN npm i
    RUN npx telescope transpile --protoDirs=./proto --outPath=./src/codegen --includeAminos=true --includeLCDClients=true --includeRPCClients=true
    SAVE ARTIFACT ./src/codegen AS LOCAL ./src/codegen
    SAVE ARTIFACT ./proto AS LOCAL ./proto

publish:
    ARG NPM_TOKEN
    FROM +codegen
    RUN npm config set registry https://registry.npmjs.org/
    RUN npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
    RUN npm version patch
    RUN npm publish
    SAVE ARTIFACT ./package.json AS LOCAL ./package.json
