VERSION 0.6
FROM node:lts-alpine
WORKDIR /app/empowerjs

# Used by root frontend Earthfile (to not get too many files and stuff)
project-setup:
  COPY proto proto
  COPY scripts scripts
  COPY src src
  COPY test test
  COPY .babelrc.js .babelrc.js
  COPY package.json package.json
  COPY tsconfig.json tsconfig.json
  SAVE ARTIFACT .

cosmwasm-codegen:
    FROM ../+frontend-install
    WORKDIR /app/empowerjs
    COPY ../../+get-cw-schema/* .
    RUN npx @cosmwasm/ts-codegen@0.25.2 generate \
      --plugin client \
      --schema ./schema \
      --out ./src/plastic-credit-marketplace \
      --name "Plastic Credit Marketplace" \
      --bundle true \
      --bundleFile index.ts \
      --bundleScope contracts
    SAVE ARTIFACT ./src/plastic-credit-marketplace AS LOCAL ./src/plastic-credit-marketplace

proto-codegen:
    FROM ../+frontend-install
    WORKDIR /app/empowerjs
    COPY ../../+get-proto/* ./proto
    RUN npm run codegen
    SAVE ARTIFACT ./src/codegen AS LOCAL ./src/codegen
    SAVE ARTIFACT ./proto AS LOCAL ./proto

codegen-all:
    BUILD +cosmwasm-codegen
    BUILD +proto-codegen
