VERSION 0.6
FROM earthly/dind:ubuntu
WORKDIR /empowerchain/testnets/circulus-1

test-collect-gentx:
    FROM ../../chain/+build
    WORKDIR /empowerchain/chain/build
    RUN ./empowerd init empower
    COPY ./gentx/ /root/.empowerchain/config/gentx/
    COPY collect-gentxs.sh .
    RUN ./collect-gentxs.sh