VERSION 0.6
FROM earthly/dind:ubuntu
WORKDIR /empowerchain/testnets/circulus-1

test-collect-gentx:
    FROM ../../chain/+build
    WORKDIR /empowerchain/chain/build
    RUN ./empowerd init empower
    COPY ./genesis.json /root/.empowerchain/config/genesis.json
    COPY ./gentx/ /root/.empowerchain/config/gentx/
    RUN ./empowerd genesis collect-gentxs