VERSION 0.6
FROM node:lts-hydrogen
WORKDIR /empowerchain/docs

build:
# New section directory should be added here manually
    COPY api-docs .
    COPY introduction .
# ===================================================
    COPY static .
    COPY index.md .
    COPY package.json .
    RUN npm install
    RUN npm run build
    SAVE ARTIFACT .vitepress/dist AS LOCAL public

docgen:
    COPY ../chain/+docgen/* ./
    SAVE ARTIFACT .vitepress/* AS LOCAL .vitepress/
    SAVE ARTIFACT cli-docs AS LOCAL cli-docs
    SAVE ARTIFACT module-docs AS LOCAL module-docs

swagger-docs:
    COPY ../chain/+swagger-gen/markdown.md ./api-docs/swagger.md
    SAVE ARTIFACT api-docs AS LOCAL api-docs

docs-gen-all:
    BUILD +swagger-docs
    BUILD +docgen