VERSION 0.6
FROM node:lts-hydrogen
WORKDIR /empowerchain/docs

build:
# New section directory should be added here manually
    COPY api_docs .
    COPY introduction .
# ===================================================
    COPY static .
    COPY index.md .
    COPY package.json .
    RUN npm install
    RUN npm run docs:build
    SAVE ARTIFACT .vitepress/dist AS LOCAL public