name: "Test EmpowerChain"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'chain/**'

jobs:
  test:
    name: Test EmpowerChain
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions-setup@v1
        with:
          version: v0.6.30

      - run: earthly --ci --output +test-with-coverage
        working-directory: ./chain

      - uses: codecov/codecov-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./chain
          flags: chain
          fail_ci_if_error: true

  smoke-test:
    - uses: actions/checkout@v3

    - uses: earthly/actions-setup@v1
      with:
        version: v0.6.30

    - run: earthly --ci +smoketest
      working-directory: ./chain

  non-determinism-test:
    - uses: actions/checkout@v3

    - uses: earthly/actions-setup@v1
      with:
        version: v0.6.30

    - run: earthly --ci +test-sim-nondeterminism
      working-directory: ./chain