name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'chain/**' 

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions-setup@v1
        with:
          version: 0.6.30

      - run: earthly --ci +lint
        working-directory: ./chain
