name: "Test CosmWasm contracts"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'cosmwasm/**'

jobs:
  test:
    name: Test CosmWasm Contracts
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions-setup@v1
        with:
          version: 0.6.30

      - run: earthly --ci --output +test-with-coverage
        working-directory: ./cosmwasm

      - uses: codecov/codecov-action@v3
        if: ${{ github.actor != 'dependabot[bot]' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./cosmwasm
          flags: cosmwasm
          fail_ci_if_error: true
