name: "Test CosmWasm contracts"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'cosmwasm/**'

jobs:
  test:
    name: Test CosmWasm Contracts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci --output +test-with-coverage
        working-directory: ./cosmwasm

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./cosmwasm
          flags: cosmwasm
          fail_ci_if_error: true
