name: "Marketplace frontend build"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'frontend/marketplace/**'

jobs:
  build:
    name: Build Marketplace Frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - uses: earthly/actions-setup@v1
        with:
          version: 0.6.30

      - run: npm ci && npm run build
        working-directory: ./frontend/marketplace