name: "Deploy Marketplace Frontend - testnet"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/marketplace/**'

jobs:
  build:
    name: Deploy Marketplace Frontend - testnet
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Load Environment Variables
        env:
          DOTENV_PATH: .env.test
        run: |
          echo "Loading environment variables from $DOTENV_PATH"
          cat $DOTENV_PATH | while read line
          do
            export $line
          done
        working-directory: ./frontend/marketplace/
      - run: npm ci && npm run build
        working-directory: ./frontend/marketplace
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          VITE_REVISION_ID: ${{ github.sha }}
          VITE_ROLLBAR_ACCESS_TOKEN: ${{ secrets.MARKETPLACE_ROLLBAR_ACCESS_TOKEN }}


      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_MARKETPLACE}}
          working-directory: ./frontend/marketplace/