name: "Deploy PoE Frontend"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/proof-of-existence/**'

jobs:
  build:
    name: Deploy Proof of Existence Frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: npm ci && npm run build
        working-directory: ./frontend/proof-of-existence/
        env:
          VITE_CHAIN_ID: circulus-1
          VITE_RPC_URL: https://empower-testnet-rpc.polkachu.com/
          VITE_REST_URL: https://empower-testnet-api.polkachu.com/
          VITE_REVISION_ID: ${{ github.sha }}
          VITE_ENVIRONMENT: testnet
          VITE_ROLLBAR_ACCESS_TOKEN: ${{ secrets.POE_ROLLBAR_ACCESS_TOKEN }}

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_POE}}
          working-directory: ./frontend/proof-of-existence/