name: "Deploy Marketplace Frontend"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/marketplace/**'

jobs:
  build:
    name: Deploy Marketplace Frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: npm ci && npm run build
        working-directory: ./frontend/marketplace

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_MARKETPLACE}}
          working-directory: ./frontend/marketplace/