name: "Deploy Marketplace Frontend - mainnet"

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy Marketplace Frontend - mainnet
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: ./frontend/marketplace
          mode: prod
      - run: npm ci && npm run build
        working-directory: ./frontend/marketplace
        env:
          VITE_REVISION_ID: ${{ github.sha }}
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_MARKETPLACE_MAINNET}}
          working-directory: ./frontend/marketplace/