name: "Deploy Airdrop Frontend"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/empower-airdrop-checker/**'

jobs:
  build:
    name: Deploy Airdrop Frontend
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - run: npm ci && npm run build
        working-directory: ./frontend/empower-airdrop-checker
        env:
          VITE_CHAIN_ID: "empowerchain-1"
          VITE_CHAIN_NAME: "EmpowerChain"
          VITE_RPC_ENDPOINT: "https://rpc.empowerchain.io:26657"
          VITE_REST_ENDPOINT: "https://api.empowerchain.io:1317"

      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          scope: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_AIRDROP}}
          working-directory: ./frontend/empower-airdrop-checker/