name: CI
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'testnets/altruistic-1/gentx/**.json'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 14.18.1
          
      - id: files
        name: Check gentx
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          readarray -t added_modified_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added_modified }}')"
          if [[ ${#added_modified_files[@]} > 1 ]]; then
            echo "More than one file found"
            exit 1
          fi
          for added_modified_file in ${added_modified_files[@]}; do
            node altruistic-1/gentx-checker.js ${added_modified_file}
          done
