name: "TypeScript types update"

on:
  push:
    branches:
      - main
    paths:
      - 'chain/proto/**' # On updating proto

jobs:
  build:
    name: Update empowerchain-ts-client types
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.22

      - run: earthly --ci --output +generate-ts-types
        working-directory: ./frontend/ts-client

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Update ts-client types
          title: Update ts-client types
          branch: update-ts-types
